In [9]:
print('hello  world')

hello  world


### Import biblioteki numpy

In [17]:
import numpy as np

### Pierwsze tablice NumPy

<h1>kod - da sięuzywać w MarkDonw HTMLa</h1>

### Tablica 1D

In [13]:
arr1d = np.array([1, 2, 3])  #mamy zadeklarowaną tablice 1 wymiarową - arr1d
arr1d

array([1, 2, 3])

In [14]:
type(arr1d)  #jaki typ zmiennej w tablicy 1-wymiarowej - ma jeden nawias kwadratowy

numpy.ndarray

### Tablica 2D

In [15]:
arr2d = np.array([[1, 2], [3, 4]])  # tablica 2-wymiarowa - ma dwa nawiasy kwadratowe
arr2d

array([[1, 2],
       [3, 4]])

In [16]:
arr2d

array([[1, 2],
       [3, 4]])

### Tablica 3D

In [ ]:
arr3d = np.array([[[1, 2], [3, 4]], [[4, 5],[6, 7]]]) # - ma trzy nawias kwadratowy
arr3d

## Wymiary tablic

In [ ]:
arr1d.ndim

In [ ]:
arr2d.ndim

In [ ]:
arr3d.ndim

### Kształty Tablicy - ich wymiarowość

arr1d.shape

In [ ]:
arr2d.shape

In [ ]:
arr3d.shape

### Typy danych jakie są wewnątrz tablic

In [ ]:
arr1d.dtype # mamy 32 bitowy integer

In [ ]:
arr_float = np.array([1.1, 2.9]) #nowa tablica ze zmienną float
arr_float

In [ ]:
arr_float.dtype

In [ ]:
arr_bool = np.array([True,False]) #nowa tablica ze zmienną bool
arr_bool

In [ ]:
arr_bool.dtype

In [ ]:
arr_int = np.array([1.5, 2.4], dtype='int')#nowa tablica ze zmienną float, ale zadeklarowlaismy że chcemy przechowyać w tej tablicy wartosci nie float, ale initger
arr_int

In [ ]:
arr_int.dtype

### Funkcje tworzące tablice

In [ ]:
np.arange(1, 11) # zmiana co jeden

In [ ]:
np.arange(1, 20, 3) # zmiana co trzy - ten osttani parametr

In [ ]:
np.zeros(3) # tu mamy tablice 1-wymairową, która ma 3 elementy o wartości 0

In [ ]:
np.zeros([2, 3]) # tu mamy tablice 2-wymairową, która ma 6 elementy o wartości 0

In [ ]:
np.ones([2,3]) # tu mamy tablice 2-wymairową, która ma 6 elementy o wartości 1

In [ ]:
np.linspace(0, 10, 3)

In [ ]:
np.linspace(0,10,50)

In [ ]:
np.full([2,2], 3) # uzyskamy tablice 2 na 2, ktora będzie wypelniona trojkami

### Podstawowe operacje na tablicach

In [ ]:
a = np.array([3,4,5,6]) # tworzymy dwie tablice a i b
b = np.array([-1, 2, 4, 1])

In [ ]:
print(a) # teraz wyświetlamy te tablice
print(b)

In [ ]:
a + b # ponizej dodajemy, odejmujemy i mnozymy tablice

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
a + 1 # dokazdego elem. tabl. a zostanie dodane 1

### Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(5)

In [ ]:
np.random.randn()

In [ ]:
np.random.rand()

In [ ]:
np.random.randn(10)

In [ ]:
np.random.randint(10, 20)

In [ ]:
np.random.choice(['a', 'b', 'c', 'd']) # losuje nam 1 wartośc z tej tablicy