In [2]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
arr = np.arange(1, 16) # tworzymy tablice 'arr'
arr

NameError: name 'np' is not defined

### Wybór elementu po indeksie

In [4]:
arr[2] #z racji, ze indeksy zaczynaja sie od 0, to mamy wartosc 3, kt ra jest równ indeksowi 2

3

In [5]:
arr[2:5]

array([3, 4, 5])

In [6]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

### Przypisywanie nowej wartości

In [7]:
arr # patrzy,my jak nasza tablica arr wygląda

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
arr[0] = 100 # w indeksie 0, zmenilismy wartość z 1 na 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [10]:
arr[10:12] = 200
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200, 200,  13,
        14,  15])

### Zmiana kształtu

In [12]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
arr2d = arr.reshape([3, 5])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Maski logiczne

In [14]:
arr_rnd = np.random.randn(3,5)
arr_rnd

array([[-0.17065317,  0.64770034, -0.58926974,  0.25942042,  0.93009447],
       [-0.8148898 , -1.49755243, -0.47958735, -0.09367471,  0.68926028],
       [ 0.71246766,  0.62952935,  0.90755645, -0.87247469,  1.02842575]])

In [15]:
arr_bool = arr_rnd >0 # to jest maska na powyższą tablicę, ktorej zadaniem jest przefiltrowanie tej powyzeszj tablicy które wartosi są dodanmit ktore ujemne
arr_bool

array([[False,  True, False,  True,  True],
       [False, False, False, False,  True],
       [ True,  True,  True, False,  True]])

In [16]:
arr_rnd[arr_bool]

array([0.64770034, 0.25942042, 0.93009447, 0.68926028, 0.71246766,
       0.62952935, 0.90755645, 1.02842575])

In [17]:
arr_rnd[arr_rnd > 0]

array([0.64770034, 0.25942042, 0.93009447, 0.68926028, 0.71246766,
       0.62952935, 0.90755645, 1.02842575])

In [18]:
arr_rnd [arr_rnd < 0]

array([-0.17065317, -0.58926974, -0.8148898 , -1.49755243, -0.47958735,
       -0.09367471, -0.87247469])